# Statistics and Probability Analysis

## Import Libraries

In [2]:
import pandas as pd
import numpy as np

## Load Feature-Engineered Dataset

In [3]:
df = pd.read_csv("../06_feature_engineering/feature_engineered_superstore.csv")

In [4]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

## Descriptive Statistics

In [5]:
df.describe()

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit,Year,Quarter,Shipping Days,Profit Margin,Average Selling Price
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2016-04-30 00:07:12.259355,2016-05-03 23:06:58.571142,55190.379428,229.858001,3.789574,0.156203,28.656896,2015.722233,2.882329,3.958175,12.031393,60.919569
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000,2014.000000,1.000000,0.000000,-275.000000,0.336000
25%,2499.250000,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750,2015.000000,2.000000,3.000000,7.500000,5.470000
50%,4997.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500,2016.000000,3.000000,4.000000,27.000000,16.270000
75%,7495.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000,2017.000000,4.000000,5.000000,36.250000,63.940000
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000,2017.000000,4.000000,7.000000,50.000000,3773.080000
std,2885.163629,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108,1.123555,1.058086,1.747567,46.675435,142.927440

## Mean

In [6]:
print("Mean Sales:", df["Sales"].mean())
print("Mean Profit:", df["Profit"].mean())
print("Mean Quantity:", df["Quantity"].mean())

Mean Sales: 229.85800083049827
Mean Profit: 28.65689630778467
Mean Quantity: 3.789573744246548

## Median

In [7]:
print("Median Sales:", df["Sales"].median())
print("Median Profit:", df["Profit"].median())

Median Sales: 54.489999999999995
Median Profit: 8.6665

## Mode

In [8]:
print(df["Ship Mode"].mode())
print(df["Category"].mode())

0    Standard Class
Name: Ship Mode, dtype: str
0    Office Supplies
Name: Category, dtype: str

## Variance

In [9]:
print("Sales Variance:", df["Sales"].var())
print("Profit Variance:", df["Profit"].var())

Sales Variance: 388434.45530807565
Profit Variance: 54877.79805537892

## Standard Deviation

In [10]:
print("Sales Std Dev:", df["Sales"].std())
print("Profit Std Dev:", df["Profit"].std())

Sales Std Dev: 623.2451005086808
Profit Std Dev: 234.2601076909573

## Quartiles

In [11]:
print(df["Sales"].quantile([0.25, 0.50, 0.75]))

0.25     17.28
0.50     54.49
0.75    209.94
Name: Sales, dtype: float64

## Interquartile Range (IQR)

In [12]:
Q1 = df["Sales"].quantile(0.25)
Q3 = df["Sales"].quantile(0.75)

IQR = Q3 - Q1

print("IQR:", IQR)

IQR: 192.66

## Skewness

In [13]:
print("Sales Skewness:", df["Sales"].skew())
print("Profit Skewness:", df["Profit"].skew())

Sales Skewness: 12.97275234181623
Profit Skewness: 7.561431562468341

## Correlation

In [14]:
df[["Sales", "Profit", "Quantity", "Discount"]].corr()

             Sales    Profit  Quantity  Discount
Sales     1.000000  0.479064  0.200795 -0.028190
Profit    0.479064  1.000000  0.066253 -0.219487
Quantity  0.200795  0.066253  1.000000  0.008623
Discount -0.028190 -0.219487  0.008623  1.000000

# Probability Examples

## Probability that an order belongs to the Technology category

In [15]:
technology_probability = (
    df["Category"] == "Technology"
).mean()

print("P(Technology):", technology_probability)

P(Technology): 0.18481088653191916

## Probability that an order is from the West region

In [16]:
west_probability = (
    df["Region"] == "West"
).mean()

print("P(West):", west_probability)

P(West): 0.32049229537722634

## Conditional Probability

Probability that an order is Technology, given that it is from the West region:

In [17]:
west_orders = df[df["Region"] == "West"]

conditional_probability = (
    west_orders["Category"] == "Technology"
).mean()

print("P(Technology | West):", conditional_probability)

P(Technology | West): 0.18701217608492038